services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PASS123!
      MYSQL_DATABASE: FastAPIDemo
      MYSQL_USER: user
      MYSQL_PASSWORD: PASS123!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pPASS123!" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  mysql_data:
