@baseUrl = http://127.0.0.1:8000
# Sau khi login thành công ở file login.http, hãy copy access_token và dán vào đây
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0dXNlcjEiLCJleHAiOjE3NzQzMzM1NDF9.oolxHaEFYzNApoKY4j2Z-YbH-VYvvuwxl0OlrRo17sQ

### Lấy thông tin User hiện tại (Me)
GET {{baseUrl}}/me
Authorization: Bearer {{authToken}}